# Regression and Model Validation
Regression
----------------------------------------
The data "students2014" is about the students attitude toward statistics. The data consists of information about students' gender, student ages, deep approach(deep), surface appoarch(surf), strategic approach(stra), attitude toward statistics, points from exam and the students' gender. WIth the data "students2014", you can figure out that what variables affect the exam points through linear regression analysis.*


You can read the data and name the data "students2014" with the code "read.table"

*students2014<-read.table("http://s3.amazonaws.com/assets.datacamp.com/production/course_2218/datasets/learning2014.txt", sep=",", header=TRUE )*


Through the codes "dim()" and "str()", you can take a look at the dimension and structure of data.

*dim(students2014)*

*str(students2014)*


You can compare all variables to find out what variable affect the most to the exam points, how the variables are distributed and how they are related to using the code "ggpairs()". 

*library(GGally)*
*library(ggplot2)*

*pairs(students2014[-1], col=(students2014$gender))*
*p <- ggpairs(students2014, mapping = aes(col=gender, alpha=0.3), lower = list(combo = wrap("facethist", bins = 20)))*
*p*

In outputs, three variables,"attitude", "stra" and "surf" are the most correlated to the exam points, and looks linear. To test the liearity, we will fte a model with three variables.  


*model1<-lm(points ~ attitude+stra+surf, data=students2014)*
*summary(model1)*

Output of the summary of model1
----------------------------------------------------------------------
Call:
lm(formula = points ~ attitude + stra + surf, data = students2014)

Residuals:
     Min       1Q   Median       3Q      Max 
-17.1550  -3.4346   0.5156   3.6401  10.8952 

Coefficients:
            Estimate Std. Error t value Pr(>|t|)
(Intercept)  11.0171     3.6837   2.991  0.00322
attitude      3.3952     0.5741   5.913 1.93e-08
stra          0.8531     0.5416   1.575  0.11716
surf         -0.5861     0.8014  -0.731  0.46563
               
(Intercept) ** 
attitude    ***
stra           
surf           
---
Signif. codes:  
0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 5.296 on 162 degrees of freedom
Multiple R-squared:  0.2074,	Adjusted R-squared:  0.1927 
F-statistic: 14.13 on 3 and 162 DF,  p-value: 3.156e-08


In this model, "Stra" and "suft" among three explanatory variables are not significantly related to exam points based on p-value. So, excluding the two variables, the model is fitted with "attitude" once again. 


*model2<-lm(points ~ attitude, data=students2014)*
*summary(model2)*

Output of the model2
--------------------------------------------------------------
Call:
lm(formula = points ~ attitude, data = students2014)

Residuals:
     Min       1Q   Median       3Q      Max 
-16.9763  -3.2119   0.4339   4.1534  10.6645 

Coefficients:
            Estimate Std. Error t value Pr(>|t|)    
(Intercept)  11.6372     1.8303   6.358 1.95e-09 ***
attitude      3.5255     0.5674   6.214 4.12e-09 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 5.32 on 164 degrees of freedom
Multiple R-squared:  0.1906,	Adjusted R-squared:  0.1856 
F-statistic: 38.61 on 1 and 164 DF,  p-value: 4.119e-09

In model2, the summary indicates that the relationship between the exam point and attitude is significant correlated at 0.00000000412 p-value. And the mulitple R-squared value is 0.1906 so this model can explain 20% of the relataionship between the exam points and attitude.


Assumption of Model and Model validation
------------------------------------------
By analyzing the residuals of the model, you can explore the validity of the model assumptions. 
*par(mfrow=c(2,2))*
*plot(model2, which = c(1,2,5))*

In the plot " residutals vs FItted values", the variace are constant. But, some values look outliers. In leverage of observations, there are still some outliers affecting errors. 
In normality of Q-Q plot, the residulass are linearly distributed, which means the errors of the model are normally distributed.  


